#!/bin/bash
set -o nounset

# die MESSAGE
function die {
   if [ -n "$1" ]; then
      echo "$1" >&2
   else
      echo "Unexpected error. Exiting.">&2
   fi
   exit 1
}

#------------------------------------------------------------------------------------
# PASS=? dr_compress ARCHIVENAME

if [ "$#" -ne 1 ]; then die "PASS=? dr_compress ARCHIVENAME" ; fi

SOURCEFOLDER="/src"
ARCHIVEPATH="/dst/$1"

if [ -e "$ARCHIVEPATH" ]; then die "Archive $1 already exists. Aborting." ; fi
if [ ! -d "$SOURCEFOLDER" ]; then die "dr_compress: Source folder does not exist: $SOURCEFOLDER"; fi

# default to empty string if doesn't exist, then test for empty string.
if [ -n "${PASS-}" ]; then
   tar cz -C "$SOURCEFOLDER" . | openssl enc -aes-256-cbc -e -k "${PASS}" > "$ARCHIVEPATH"
   [ $? -eq 0 ] || die "Failed to create encrypted archive."
else
   echo "WARNING: No password supplied. Backup is not encrypted!">&2
   tar czf "$ARCHIVEPATH" -C "$SOURCEFOLDER" .
   [ $? -eq 0 ] || die "Failed to create archive."
fi
