#!/bin/bash
set -o nounset

# die MESSAGE
function die {
   [ -n "$1" ] || { echo "Unexpected error. Exiting."<&2 ; exit 1 ; }

   echo "$1" <&2
   exit 1
}

#------------------------------------------------------------------------------------
# PASS=? dr_decompress ARCHIVENAME

[ "$#" -eq 1 ] || die "dr_decompress_fast ARCHIVENAME"

DESTFOLDER="/dst"
ARCHIVEPATH="/src/$1"

if [ ! -e "$ARCHIVEPATH" ]; then ls /src ; die "dr_decompress: No such archive: $ARCHIVEPATH"; fi
if [ ! -d "$DESTFOLDER" ]; then die "dr_decompress: Destination folder does not exist: $DESTFOLDER"; fi

tar -xpf "${ARCHIVEPATH}" -C "${DESTFOLDER}" >/dev/null 2>&1
[ $? -eq 0 ] || die "Failed to decompress archive. The password may be incorrect!"
